#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  ABREX
#      AUTOSAR BSW and RTE XML Generator
#
#  Copyright (C) 2013-2016 by Center for Embedded Computing Systems
#              Graduate School of Information Science, Nagoya Univ., JAPAN
#  Copyright (C) 2014-2016 by AISIN COMCRUISE Co., Ltd., JAPAN
#  Copyright (C) 2014-2016 by eSOL Co.,Ltd., JAPAN
#  Copyright (C) 2013-2016 by FUJI SOFT INCORPORATED, JAPAN
#  Copyright (C) 2014-2016 by NEC Communication Systems, Ltd., JAPAN
#  Copyright (C) 2013-2016 by Panasonic Advanced Technology Development Co., Ltd., JAPAN
#  Copyright (C) 2013-2014 by Renesas Electronics Corporation, JAPAN
#  Copyright (C) 2014-2016 by SCSK Corporation, JAPAN
#  Copyright (C) 2013-2016 by Sunny Giken Inc., JAPAN
#  Copyright (C) 2015-2016 by SUZUKI MOTOR CORPORATION
#  Copyright (C) 2013-2016 by TOSHIBA CORPORATION, JAPAN
#  Copyright (C) 2013-2016 by Witz Corporation
#
#  上記著作権者は，以下の(1)〜(4)の条件を満たす場合に限り，本ソフトウェ
#  ア（本ソフトウェアを改変したものを含む．以下同じ）を使用・複製・改
#  変・再配布（以下，利用と呼ぶ）することを無償で許諾する．
#  (1) 本ソフトウェアをソースコードの形で利用する場合には，上記の著作
#      権表示，この利用条件および下記の無保証規定が，そのままの形でソー
#      スコード中に含まれていること．
#  (2) 本ソフトウェアを，ライブラリ形式など，他のソフトウェア開発に使
#      用できる形で再配布する場合には，再配布に伴うドキュメント（利用
#      者マニュアルなど）に，上記の著作権表示，この利用条件および下記
#      の無保証規定を掲載すること．
#  (3) 本ソフトウェアを，機器に組み込むなど，他のソフトウェア開発に使
#      用できない形で再配布する場合には，次のいずれかの条件を満たすこ
#      と．
#    (a) 再配布に伴うドキュメント（利用者マニュアルなど）に，上記の著
#        作権表示，この利用条件および下記の無保証規定を掲載すること．
#    (b) 再配布の形態を，別に定める方法によって，TOPPERSプロジェクトに
#        報告すること．
#  (4) 本ソフトウェアの利用により直接的または間接的に生じるいかなる損
#      害からも，上記著作権者およびTOPPERSプロジェクトを免責すること．
#      また，本ソフトウェアのユーザまたはエンドユーザからのいかなる理
#      由に基づく請求からも，上記著作権者およびTOPPERSプロジェクトを
#      免責すること．
#
#  本ソフトウェアは，AUTOSAR（AUTomotive Open System ARchitecture）仕
#  様に基づいている．上記の許諾は，AUTOSARの知的財産権を許諾するもので
#  はない．AUTOSARは，AUTOSAR仕様に基づいたソフトウェアを商用目的で利
#  用する者に対して，AUTOSARパートナーになることを求めている．
#
#  本ソフトウェアは，無保証で提供されているものである．上記著作権者お
#  よびTOPPERSプロジェクトは，本ソフトウェアに関して，特定の使用目的
#  に対する適合性も含めて，いかなる保証も行わない．また，本ソフトウェ
#  アの利用により直接的または間接的に生じたいかなる損害に関しても，そ
#  の責任を負わない．
#

import argparse
import os
import re
import sys
import xml.etree.ElementTree as ET
from collections import OrderedDict

import yaml


######################################################################
# 定数定義
######################################################################
TOOL_ROOT = os.path.dirname(os.path.abspath(__file__))

VERSION = "1.1.1"
VER_INFO = " Generated by ABREX Ver. {0} ".format(VERSION)
XML_ROOT_PATH = "/AUTOSAR/EcucDefs/"
XML_EDITION = "4.2.0"
XML_SNAME = "SHORT-NAME"
XML_PARAM = "PARAMETER-VALUES"
XML_REFER = "REFERENCE-VALUES"
XML_SUB = "SUB-CONTAINERS"
XML_AUTOSAR_FIXED_ATT = OrderedDict([
    ("xmlns", "http://autosar.org/schema/r4.0"),
    ("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance"),
    ("xsi:schemaLocation",
     "http://autosar.org/schema/r4.0 AUTOSAR_4-0-3_STRICT.xsd"),
])

# パラメータデータ型種別格納辞書
# (これ以外はすべてECUC-NUMERICAL-PARAM-VALUE)
XML_VALUE_TYPE = {
    "ECUC-REFERENCE-DEF":               "ECUC-REFERENCE-VALUE",
    "ECUC-FOREIGN-REFERENCE-DEF":       "ECUC-REFERENCE-VALUE",
    "ECUC-SYMBOLIC-NAME-REFERENCE-DEF": "ECUC-REFERENCE-VALUE",
    "ECUC-INSTANCE-REFERENCE-DEF":      "ECUC-INSTANCE-REFERENCE-VALUE",
    "ECUC-CHOICE-REFERENCE-DEF":        "ECUC-CHOICE-REFERENCE-DEF",
    "ECUC-ENUMERATION-PARAM-DEF":       "ECUC-TEXTUAL-PARAM-VALUE",
    "ECUC-STRING-PARAM-DEF":            "ECUC-TEXTUAL-PARAM-VALUE",
    "ECUC-MULTILINE-STRING-PARAM-DEF":  "ECUC-TEXTUAL-PARAM-VALUE",
    "ECUC-FUNCTION-NAME-DEF":           "ECUC-TEXTUAL-PARAM-VALUE",
    "ECUC-LINKER-SYMBOL-DEF":           "ECUC-TEXTUAL-PARAM-VALUE",
}

# インスタンス参照型の特別コンテナ
XML_INSTANCE_REF_CONTAINER = {
    "EcucPartitionSoftwareComponentInstanceRef": OrderedDict([
        ("CONTEXT-ELEMENT-REF", "ROOT-SW-COMPOSITION-PROTOTYPE"),
        ("TARGET-REF", "SW-COMPONENT-PROTOTYPE"),
    ]),
}


######################################################################
# モジュールレベルの状態 (Ruby 版のグローバル $... と等価)
######################################################################
class _State:
    foreign_ref_type = None
    choice_container = None
    instance_ref_type = None
    ecuc = None
    dest = None
    reference_param = None
    result = None
    container_path = ""


######################################################################
# YAML ヘルパ (Ruby YAML と挙動を寄せる)
######################################################################
def _ordered_dict_representer(dumper, data):
    return dumper.represent_mapping("tag:yaml.org,2002:map", data.items())


def _str_representer(dumper, data):
    # コーテーションをなるべく出さない
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data,
                                       style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


yaml.add_representer(OrderedDict, _ordered_dict_representer)
yaml.add_representer(str, _str_representer)


def _load_yaml(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def _dump_yaml(data, file_path):
    with open(file_path, "w", encoding="utf-8", newline="\n") as f:
        yaml.dump(data, f, allow_unicode=True, default_flow_style=False,
                  sort_keys=False)


######################################################################
# XML ヘルパ
######################################################################
def _strip_ns(elem):
    """要素ツリーからネームスペースを除去 (REXML 互換動作のため)."""
    for el in elem.iter():
        tag = el.tag
        if isinstance(tag, str) and tag.startswith("{"):
            el.tag = tag.split("}", 1)[1]
        # 属性のネームスペースも除去
        new_attrib = {}
        for k, v in list(el.attrib.items()):
            if k.startswith("{"):
                new_attrib[k.split("}", 1)[1]] = v
            else:
                new_attrib[k] = v
        el.attrib = new_attrib


def _parse_xml(file_path):
    tree = ET.parse(file_path)
    root = tree.getroot()
    _strip_ns(root)
    return root


def _add_subelem(parent, tag, attrib=None, text=None):
    if attrib is None:
        attrib = {}
    el = ET.SubElement(parent, tag, attrib=attrib)
    if text is not None:
        el.text = text
    return el


def _find_text(elem, tag):
    sub = elem.find(tag)
    if sub is None:
        return None
    return sub.text


def _find_all(elem, path):
    return elem.findall(path)


def _serialize_xml(root, version_comment=None):
    """ET.Element を文字列にシリアライズし，Ruby 版の最終整形と同等の
    後処理を施す．"""
    # ET には XML 宣言と pretty-print, comment 注入機能がないため自作する．
    raw = _xml_to_string_pretty(root, indent="  ")
    out = '<?xml version="1.0" encoding="UTF-8"?>\n'
    if version_comment is not None:
        out += '<!--{0}-->\n'.format(version_comment)
    out += raw
    # 値だけが入る要素 (中身が単純テキスト) は <tag>VAL</tag> に折りたたむ
    out = re.sub(
        r">\n[\s]+([\w\.\[\]\(\)\+\-/\*~&;\s]*?)\n[\s]+<",
        r">\1<",
        out,
    )
    # インデントをタブにする
    out = out.replace("  ", "\t")
    return out


def _xml_to_string_pretty(elem, indent="  ", level=0):
    """XML 要素を文字列に整形する (簡易 pretty-print).

    属性値はダブルクォートで，子要素や text を綺麗に整形する．
    """
    pad = indent * level
    # 開きタグの組み立て
    attr_str = ""
    for k, v in elem.attrib.items():
        # 属性値中の特殊文字をエスケープ
        v_esc = (v.replace("&", "&amp;")
                  .replace("<", "&lt;")
                  .replace('"', "&quot;"))
        attr_str += ' {0}="{1}"'.format(k, v_esc)

    children = list(elem)
    text = (elem.text or "")
    text_stripped = text.strip()

    if not children and not text_stripped:
        return "{0}<{1}{2}/>\n".format(pad, elem.tag, attr_str)

    if not children:
        # テキストのみ
        text_esc = (text_stripped.replace("&", "&amp;")
                                  .replace("<", "&lt;"))
        return "{0}<{1}{2}>{3}</{1}>\n".format(
            pad, elem.tag, attr_str, text_esc)

    # 子要素あり
    out = "{0}<{1}{2}>\n".format(pad, elem.tag, attr_str)
    for c in children:
        out += _xml_to_string_pretty(c, indent, level + 1)
    out += "{0}</{1}>\n".format(pad, elem.tag)
    return out


######################################################################
# YAML → XML 実行機能
######################################################################
def yaml_to_xml(yaml_files, ecu_extract_ref, verbose):
    # 各パラメータのデータ型定義 (-pオプションで生成したものを使用する)
    s_param_file = os.path.join(TOOL_ROOT, "param_info.yaml")
    if not os.path.isfile(s_param_file):
        sys.exit("{0} not found !!".format(s_param_file))
    param_info = _load_yaml(s_param_file)
    if not isinstance(param_info, dict):
        sys.exit("not YAML file !! [{0}]".format(s_param_file))

    # 外部参照先のデータ型格納辞書を分離
    _State.foreign_ref_type = param_info.pop("FOREIGN_REF_TYPE", None) or \
        param_info.pop(":FOREIGN_REF_TYPE", None)

    # 選択型のコンテナ格納配列を分離
    _State.choice_container = param_info.pop("ECUC_CHOICE_CONTAINER_DEF",
                                              None) or \
        param_info.pop(":ECUC_CHOICE_CONTAINER_DEF", None) or []

    # インスタンス参照先のデータ型を保持
    _State.instance_ref_type = param_info.get("ECUC-INSTANCE-REFERENCE-DEF",
                                               []) or []

    # コンテナ名変換テーブル
    _State.ecuc = {}
    _State.dest = {}
    for s_type, a_param in param_info.items():
        if a_param is None:
            continue
        for s_name in a_param:
            if s_type in XML_VALUE_TYPE:
                _State.ecuc[s_name] = XML_VALUE_TYPE[s_type]
            else:
                _State.ecuc[s_name] = "ECUC-NUMERICAL-PARAM-VALUE"
            _State.dest[s_name] = s_type

    # 参照型のパラメータ一覧
    _State.reference_param = (
        (param_info.get("ECUC-REFERENCE-DEF") or []) +
        (param_info.get("ECUC-FOREIGN-REFERENCE-DEF") or []) +
        (param_info.get("ECUC-SYMBOLIC-NAME-REFERENCE-DEF") or []) +
        (param_info.get("ECUC-INSTANCE-REFERENCE-DEF") or [])
    )

    # 与えられた全 YAML をマージする
    h_yaml = OrderedDict()
    s_arxml_name = None
    for s_file_name in yaml_files:
        if not os.path.isfile(s_file_name):
            sys.exit("Argument error !! [{0}]".format(s_file_name))

        # 出力ファイル名作成 (複数ある場合，最初のファイル名を採用する)
        if os.path.splitext(s_file_name)[1] == ".yaml":
            if s_arxml_name is None:
                base = os.path.splitext(os.path.basename(s_file_name))[0]
                s_arxml_name = os.path.join(
                    os.path.dirname(s_file_name) or ".", base + ".arxml")
        else:
            sys.exit("not YAML file name !! [{0}]".format(s_file_name))

        h_tmp = _load_yaml(s_file_name)
        if not isinstance(h_tmp, dict):
            sys.exit("not YAML file !! [{0}]".format(s_file_name))

        # 読み込んだデータをマージしていく
        _yaml_to_xml_merge_hash(h_yaml, h_tmp)

    # XML ツリー組み立て
    xml_autosar = ET.Element("AUTOSAR", attrib=dict(XML_AUTOSAR_FIXED_ATT))
    xml_ar_packages = ET.SubElement(xml_autosar, "AR-PACKAGES")

    # IMPLEMENTATION-DATA-TYPE 格納辞書を分離して先に登録
    h_impl_data_type = h_yaml.pop("IMPLEMENTATION-DATA-TYPE", None)
    if h_impl_data_type is not None:
        xml_ar_package = ET.SubElement(xml_ar_packages, "AR-PACKAGE")
        _add_subelem(xml_ar_package, XML_SNAME, text="ImplementationDataTypes")
        xml_elements = ET.SubElement(xml_ar_package, "ELEMENTS")
        for s_short_name, h_data in h_impl_data_type.items():
            xml_idt = ET.SubElement(xml_elements, "IMPLEMENTATION-DATA-TYPE")
            _add_subelem(xml_idt, XML_SNAME, text=s_short_name)
            _add_subelem(xml_idt, "CATEGORY", text=h_data["CATEGORY"])

    a_module_paths = []
    for s_package_name, h_package_data in h_yaml.items():
        xml_ar_package = ET.SubElement(xml_ar_packages, "AR-PACKAGE")
        _add_subelem(xml_ar_package, XML_SNAME, text=s_package_name)
        xml_elements = ET.SubElement(xml_ar_package, "ELEMENTS")

        for s_module_name, h_module_data in h_package_data.items():
            a_module_paths.append("/{0}/{1}".format(s_package_name,
                                                     s_module_name))
            xml_module = ET.SubElement(xml_elements,
                                        "ECUC-MODULE-CONFIGURATION-VALUES")
            _add_subelem(xml_module, XML_SNAME, text=s_module_name)
            if "DefinitionRef" in h_module_data:
                s_module_def_ref = h_module_data["DefinitionRef"]
                del h_module_data["DefinitionRef"]
            else:
                if verbose:
                    print("This {0} is not defined for 'DefinitionRef'."
                          .format(s_module_name))
                s_module_def_ref = s_module_name
            _add_subelem(xml_module, "DEFINITION-REF",
                          attrib={"DEST": "ECUC-MODULE-DEF"},
                          text=XML_ROOT_PATH + s_module_def_ref)
            _add_subelem(xml_module, "ECUC-DEF-EDITION", text=XML_EDITION)
            _add_subelem(xml_module, "IMPLEMENTATION-CONFIG-VARIANT",
                          text="VARIANT-PRE-COMPILE")
            xml_containers = ET.SubElement(xml_module, "CONTAINERS")

            # 各パラメータ用コンテナを作成する
            for s_short_name, h_pi in h_module_data.items():
                if "DefinitionRef" not in h_pi:
                    h_pi["DefinitionRef"] = s_short_name
                _yaml_to_xml_make_container(
                    xml_containers, s_short_name, h_pi,
                    XML_ROOT_PATH + s_module_def_ref)

    # ECU-EXTRACT-REF 指定がある場合，<ECUC-VALUE-COLLECTION> を追加する
    if ecu_extract_ref is not None:
        xml_ar_package = ET.SubElement(xml_ar_packages, "AR-PACKAGE")
        _add_subelem(xml_ar_package, XML_SNAME, text="EcucValueCollection")
        xml_elements = ET.SubElement(xml_ar_package, "ELEMENTS")
        xml_evc = ET.SubElement(xml_elements, "ECUC-VALUE-COLLECTION")
        _add_subelem(xml_evc, XML_SNAME, text="EcucValueCollection")
        _add_subelem(xml_evc, "ECU-EXTRACT-REF",
                      attrib={"DEST": "SYSTEM"}, text=ecu_extract_ref)
        xml_values = ET.SubElement(xml_evc, "ECUC-VALUES")
        for s_path in a_module_paths:
            xml_cond = ET.SubElement(
                xml_values,
                "ECUC-MODULE-CONFIGURATION-VALUES-REF-CONDITIONAL")
            _add_subelem(xml_cond,
                          "ECUC-MODULE-CONFIGURATION-VALUES-REF",
                          attrib={
                              "DEST": "ECUC-MODULE-CONFIGURATION-VALUES"},
                          text=s_path)

    # XML 文字列生成
    s_xml = _serialize_xml(xml_autosar, version_comment=VER_INFO)

    # ファイル出力
    with open(s_arxml_name, "w", encoding="utf-8", newline="\n") as fp:
        fp.write(s_xml)

    print("Generated {0}".format(s_arxml_name))


def _yaml_to_xml_merge_hash(h_base, h_add):
    for s_key, x_val in h_add.items():
        if s_key not in h_base:
            h_base[s_key] = x_val
        elif h_base[s_key] != x_val:
            if isinstance(h_base[s_key], dict) and isinstance(x_val, dict):
                _yaml_to_xml_merge_hash(h_base[s_key], x_val)
            elif isinstance(h_base[s_key], list):
                if isinstance(x_val, list):
                    h_base[s_key].extend(x_val)
                else:
                    h_base[s_key].append(x_val)
            elif isinstance(x_val, list):
                h_base[s_key] = [h_base[s_key]] + list(x_val)
            else:
                h_base[s_key] = [h_base[s_key], x_val]
        # 同値ならなにもしない


def _yaml_to_xml_make_container(parent, s_short_name, h_param_info, s_path):
    # "ECUC-CONTAINER-VALUE" 要素を作成
    cContainer = ET.SubElement(parent, "ECUC-CONTAINER-VALUE")
    _add_subelem(cContainer, XML_SNAME, text=s_short_name)

    def_ref = h_param_info["DefinitionRef"]
    if def_ref in (_State.choice_container or []):
        _add_subelem(cContainer, "DEFINITION-REF",
                      attrib={"DEST": "ECUC-CHOICE-CONTAINER-DEF"},
                      text="{0}/{1}".format(s_path, def_ref))
    else:
        _add_subelem(cContainer, "DEFINITION-REF",
                      attrib={"DEST": "ECUC-PARAM-CONF-CONTAINER-DEF"},
                      text="{0}/{1}".format(s_path, def_ref))

    # 各パラメータ設定 (パラメータが無い場合は不要)
    if len(h_param_info) == 1:
        return cContainer

    h_check = {XML_PARAM: None, XML_REFER: None, XML_SUB: None}

    # まず参照型，サブコンテナ以外を生成 (AUTOSAR スキーマ制約)
    for s_param_name, sah_value in h_param_info.items():
        if s_param_name == "DefinitionRef" or isinstance(sah_value, dict):
            continue

        if s_param_name in (_State.reference_param or []):
            continue

        # パラメータ名チェック
        if (s_param_name not in (_State.ecuc or {}) or
                s_param_name not in (_State.dest or {})):
            sys.exit("Unknown parameter: {0}".format(s_param_name))

        if h_check[XML_PARAM] is None:
            h_check[XML_PARAM] = ET.SubElement(cContainer, XML_PARAM)

        # 多重度 * 対応
        a_temp = sah_value if isinstance(sah_value, list) else [sah_value]
        for s_val in a_temp:
            ec_type = _State.ecuc[s_param_name]
            xml_p = ET.SubElement(h_check[XML_PARAM], ec_type)
            _add_subelem(xml_p, "DEFINITION-REF",
                          attrib={"DEST": _State.dest[s_param_name]},
                          text="{0}/{1}/{2}".format(
                              s_path, def_ref, s_param_name))
            _add_subelem(xml_p, "VALUE", text=str(s_val))

    # 次に参照型を生成 (AUTOSAR スキーマ制約)
    for s_param_name, sah_value in h_param_info.items():
        if s_param_name == "DefinitionRef" or isinstance(sah_value, dict):
            continue

        if s_param_name in (_State.instance_ref_type or []):
            if not isinstance(sah_value, list):
                sys.exit("{0} must be Array !!".format(s_param_name))
            if s_param_name not in XML_INSTANCE_REF_CONTAINER:
                sys.exit("{0} is not supported !!".format(s_param_name))

            if h_check[XML_REFER] is None:
                h_check[XML_REFER] = ET.SubElement(cContainer, XML_REFER)

            # 多重度 * 対応 (2 次元配列かチェック)
            if (sah_value and isinstance(sah_value[0], list)):
                a_temp = sah_value
            else:
                a_temp = [sah_value]
            for a_val in a_temp:
                ec_type = _State.ecuc[s_param_name]
                xml_p = ET.SubElement(h_check[XML_REFER], ec_type)
                _add_subelem(xml_p, "DEFINITION-REF",
                              attrib={"DEST": _State.dest[s_param_name]},
                              text="{0}/{1}/{2}".format(
                                  s_path, def_ref, s_param_name))
                xml_iref = ET.SubElement(xml_p, "VALUE-IREF")
                for h_val in a_val:
                    for s_p, s_d in XML_INSTANCE_REF_CONTAINER[
                            s_param_name].items():
                        if s_p in h_val:
                            _add_subelem(xml_iref, s_p,
                                          attrib={"DEST": s_d},
                                          text=str(h_val[s_p]))

        elif s_param_name in (_State.reference_param or []):
            if h_check[XML_REFER] is None:
                h_check[XML_REFER] = ET.SubElement(cContainer, XML_REFER)

            a_temp = sah_value if isinstance(sah_value, list) else [sah_value]
            for s_val in a_temp:
                ec_type = _State.ecuc[s_param_name]
                xml_p = ET.SubElement(h_check[XML_REFER], ec_type)
                _add_subelem(xml_p, "DEFINITION-REF",
                              attrib={"DEST": _State.dest[s_param_name]},
                              text="{0}/{1}/{2}".format(
                                  s_path, def_ref, s_param_name))
                if (_State.foreign_ref_type and
                        s_param_name in _State.foreign_ref_type):
                    _add_subelem(xml_p, "VALUE-REF",
                                  attrib={
                                      "DEST": _State.foreign_ref_type[
                                          s_param_name]},
                                  text=str(s_val))
                else:
                    _add_subelem(xml_p, "VALUE-REF",
                                  attrib={"DEST": "ECUC-CONTAINER-VALUE"},
                                  text=str(s_val))

    # 最後にサブコンテナを生成
    for s_param_name, sah_value in h_param_info.items():
        if s_param_name == "DefinitionRef" or not isinstance(sah_value, dict):
            continue
        if h_check[XML_SUB] is None:
            h_check[XML_SUB] = ET.SubElement(cContainer, XML_SUB)
        if "DefinitionRef" not in sah_value:
            sah_value["DefinitionRef"] = s_param_name
        _yaml_to_xml_make_container(
            h_check[XML_SUB], s_param_name, sah_value,
            "{0}/{1}".format(s_path, def_ref))

    return cContainer


######################################################################
# XML → YAML 実行機能
######################################################################
def xml_to_yaml(s_first_file, a_extra_file):
    files = [s_first_file] + list(a_extra_file)
    for s_file_name in files:
        if not os.path.isfile(s_file_name):
            sys.exit("Argument error !! [{0}]".format(s_file_name))
        if os.path.splitext(s_file_name)[1] != ".arxml":
            sys.exit("not ARXML file !! [{0}]".format(s_file_name))

        base = os.path.splitext(os.path.basename(s_file_name))[0]
        s_yaml_name = os.path.join(
            os.path.dirname(s_file_name) or ".", base + ".yaml")

        root = _parse_xml(s_file_name)
        h_result = OrderedDict()

        # /AUTOSAR/AR-PACKAGES/AR-PACKAGE 直下の各 ECUC-MODULE-...
        for c_pkg in root.findall("AR-PACKAGES/AR-PACKAGE"):
            for c_mod in c_pkg.findall(
                    "ELEMENTS/ECUC-MODULE-CONFIGURATION-VALUES"):
                s_pkg = _find_text(c_pkg, "SHORT-NAME")
                if s_pkg not in h_result:
                    h_result[s_pkg] = OrderedDict()

                s_mod = _find_text(c_mod, "SHORT-NAME")
                h_result[s_pkg][s_mod] = OrderedDict()

                for c_cont in c_mod.findall(
                        "CONTAINERS/ECUC-CONTAINER-VALUE"):
                    _xml_to_yaml_parse_parameter(
                        c_cont, h_result[s_pkg][s_mod])

        _dump_yaml(h_result, s_yaml_name)
        print("Generated {0}".format(s_yaml_name))


def _xml_to_yaml_parse_parameter(c_elem, h_target):
    s_short = _find_text(c_elem, "SHORT-NAME")
    s_def_ref = _find_text(c_elem, "DEFINITION-REF") or ""
    s_def_name = s_def_ref.split("/")[-1]
    h_target[s_short] = OrderedDict()
    if s_short != s_def_name:
        h_target[s_short]["DefinitionRef"] = s_def_name

    # パラメータ
    for c_pv in c_elem.findall("PARAMETER-VALUES"):
        for tag in ("ECUC-NUMERICAL-PARAM-VALUE",
                    "ECUC-TEXTUAL-PARAM-VALUE"):
            for c_g in c_pv.findall(tag):
                s_name = (_find_text(c_g, "DEFINITION-REF") or
                          "").split("/")[-1]
                s_val = _find_text(c_g, "VALUE")
                _xml_to_yaml_set_value(h_target[s_short], s_name, s_val)

    # 参照，外部参照，選択参照
    for c_ref in c_elem.findall(
            "REFERENCE-VALUES/ECUC-REFERENCE-VALUE"):
        s_name = (_find_text(c_ref, "DEFINITION-REF") or
                  "").split("/")[-1]
        v_ref_text = _find_text(c_ref, "VALUE-REF")
        if v_ref_text is None:
            sys.exit("<VALUE> is not found in '{0}'".format(s_short))
        _xml_to_yaml_set_value(h_target[s_short], s_name, v_ref_text)

    # インスタンス参照
    for c_iref in c_elem.findall(
            "REFERENCE-VALUES/ECUC-INSTANCE-REFERENCE-VALUE"):
        s_name = (_find_text(c_iref, "DEFINITION-REF") or
                  "").split("/")[-1]
        h_target[s_short][s_name] = []
        c_value_iref = c_iref.find("VALUE-IREF")
        if c_value_iref is not None:
            ctx = _find_text(c_value_iref, "CONTEXT-ELEMENT-REF")
            tgt = _find_text(c_value_iref, "TARGET-REF")
            h_target[s_short][s_name].append(
                OrderedDict([("CONTEXT-ELEMENT-REF", ctx)]))
            h_target[s_short][s_name].append(
                OrderedDict([("TARGET-REF", tgt)]))

    # サブコンテナ (再帰呼出し)
    for c_sub in c_elem.findall("SUB-CONTAINERS/ECUC-CONTAINER-VALUE"):
        _xml_to_yaml_parse_parameter(c_sub, h_target[s_short])


def _xml_to_yaml_set_value(target, s_name, s_value):
    """同じパラメータ名が複数回出現したら配列化する."""
    if s_name in target:
        cur = target[s_name]
        if isinstance(cur, list):
            cur.append(s_value)
        else:
            target[s_name] = [cur, s_value]
    else:
        target[s_name] = s_value


######################################################################
# AUTOSAR パラメータ情報ファイル作成
######################################################################
_NCES_CONTAINER = """\
ECUC-ENUMERATION-PARAM-DEF:
  - OsMemorySectionInitialize
  - OsIsrInterruptSource
  - OsInterCoreInterruptInterruptSource
  - OsSpinlockLockMethod
  - WdgTriggerMode
  - WdgTimeoutReaction
ECUC-INTEGER-PARAM-DEF:
  - OsMasterCoreId
  - OsHookStackSize
  - OsHookStackCoreAssignment
  - OsOsStackSize
  - OsOsStackCoreAssignment
  - OsNonTrustedHookStackSize
  - OsNonTrustedHookStackCoreAssignment
  - OsTaskStackSize
  - OsTaskSystemStackSize
  - OsIsrInterruptNumber
  - OsIsrInterruptPriority
  - OsIsrStackSize
  - OsTrustedFunctionStackSize
  - OsInterCoreInterruptStackSize
  - OsMemoryRegionSize
  - OsMemoryRegionStartAddress
  - OsMemoryAreaSize
  - OsStandardMemoryCoreAssignment
  - OsIsrMaxFrequency
  - WdgWindowOpenRate
ECUC-STRING-PARAM-DEF:
  - OsIncludeFileName
  - OsMemoryRegionName
  - OsMemoryAreaStartAddress
  - OsMemorySectionName
  - OsMemoryModuleName
  - OsLinkSectionName
  - OsIocPrimitiveDataType
  - OsIocIncludeFile
  - OsHookStackStartAddress
  - OsOsStackStartAddress
  - OsNonTrustedHookStackStartAddress
  - OsTaskStackStartAddress
  - OsTaskSystemStackStartAddress
  - OsInterCoreInterruptStackStartAddress
ECUC-BOOLEAN-PARAM-DEF:
  - OsMemoryRegionWriteable
  - OsMemoryAreaWriteable
  - OsMemoryAreaReadable
  - OsMemoryAreaExecutable
  - OsMemoryAreaCacheable
  - OsMemoryAreaDevice
  - OsMemorySectionWriteable
  - OsMemorySectionReadable
  - OsMemorySectionExecutable
  - OsMemorySectionShort
  - OsMemorySectionCacheable
  - OsMemorySectionDevice
  - OsMemorySectionExport
  - OsMemoryModuleExport
  - OsTaskOsInterruptLockMonitor
  - OsTaskResourceLockMonitor
ECUC-REFERENCE-DEF:
  - OsStandardMemoryRomRegionRef
  - OsStandardMemoryRamRegionRef
  - OsAppStandardMemoryRomRegionRef
  - OsAppStandardMemoryRamRegionRef
  - OsMemorySectionMemoryRegionRef
  - OsLinkSectionMemoryRegionRef
  - OsResourceLinkedResourceRef
  - OsCounterIsrRef
  - OsAppMemorySectionRef
  - OsAppMemoryModuleRef
  - OsAppMemoryAreaRef
  - OsAppInterCoreInterruptRef
  - OsInterCoreInterruptAccessingApplication
  - OsInterCoreInterruptResourceRef
  - WdgMOsCounterRef
  - OsSystemCycleTimeWindowRef
ECUC-FLOAT-PARAM-DEF:
  - OsSystemCycleTime
  - OsSystemCycleTimeWindowStart
  - OsSystemCycleTimeWindowLength
  - OsOsInterruptLockBudget
  - OsResourceLockBudget
  - OsTrustedFunctionExecutionBudget
  - WdgTimeout
  - WdgTriggerInterruptPeriod
"""


def make_param_info(s_file_name):
    if not os.path.isfile(s_file_name):
        sys.exit("Argument error !! [{0}]".format(s_file_name))

    s_param_file = os.path.join(
        os.path.dirname(s_file_name) or ".", "param_info.yaml")

    a_target_module = ["Rte", "Os", "Com", "PduR", "CanTp", "CanIf", "Can",
                       "EcuC", "EcuM", "WdgM", "WdgIf", "Wdg", "Dem"]

    root = _parse_xml(s_file_name)

    _State.foreign_ref_type = OrderedDict()
    _State.choice_container = []

    # NCES 仕様コンテナを予め設定
    h_result = yaml.safe_load(_NCES_CONTAINER)
    h_result_ord = OrderedDict()
    for k, v in h_result.items():
        h_result_ord[k] = list(v)
    _State.result = h_result_ord

    # /AUTOSAR/AR-PACKAGES/AR-PACKAGE/AR-PACKAGES/AR-PACKAGE/ELEMENTS/ECUC-MODULE-DEF
    for c_mod in root.findall(
            "AR-PACKAGES/AR-PACKAGE/AR-PACKAGES/AR-PACKAGE/ELEMENTS/"
            "ECUC-MODULE-DEF"):
        s_name = _find_text(c_mod, "SHORT-NAME")
        if s_name not in a_target_module:
            continue
        for c_cont in c_mod.findall(
                "CONTAINERS/ECUC-PARAM-CONF-CONTAINER-DEF"):
            _make_param_info_parse_parameter(c_cont)

    # パラメータ名でソートと重複除去
    h_sorted = OrderedDict()
    for k, v in _State.result.items():
        h_sorted[k] = sorted(set(v))

    # 外部参照先のデータ型格納辞書を結合
    if _State.foreign_ref_type:
        h_sorted["FOREIGN_REF_TYPE"] = OrderedDict(
            sorted(_State.foreign_ref_type.items()))

    # 選択型のコンテナ格納配列を追加
    if _State.choice_container:
        h_sorted["ECUC_CHOICE_CONTAINER_DEF"] = sorted(
            set(_State.choice_container))

    # RteSoftwareComponentInstanceRef は外部参照とインスタンス参照の
    # 両方に含まれるが，外部参照として扱う
    if "ECUC-INSTANCE-REFERENCE-DEF" in h_sorted:
        try:
            h_sorted["ECUC-INSTANCE-REFERENCE-DEF"].remove(
                "RteSoftwareComponentInstanceRef")
        except ValueError:
            pass

    _dump_yaml(h_sorted, s_param_file)
    print("Generated {0}".format(s_param_file))


def _make_param_info_parse_sub_container(c_elem):
    for c in list(c_elem):
        if c.tag == "ECUC-CHOICE-CONTAINER-DEF":
            _State.choice_container.append(_find_text(c, XML_SNAME))
            _make_param_info_parse_sub_container(c)
        elif c.tag == "ECUC-PARAM-CONF-CONTAINER-DEF":
            _make_param_info_parse_parameter(c)
        else:
            _make_param_info_parse_sub_container(c)


def _make_param_info_parse_parameter(c_elem):
    # パラメータ
    for c_p in c_elem.findall("PARAMETERS"):
        for c_g in list(c_p):
            if c_g.tag not in _State.result:
                _State.result[c_g.tag] = []
            _State.result[c_g.tag].append(_find_text(c_g, "SHORT-NAME"))

    # 参照
    for c_ref in c_elem.findall("REFERENCES/ECUC-REFERENCE-DEF"):
        _State.result.setdefault("ECUC-REFERENCE-DEF", []).append(
            _find_text(c_ref, "SHORT-NAME"))

    # 外部参照
    for c_ref in c_elem.findall("REFERENCES/ECUC-FOREIGN-REFERENCE-DEF"):
        _State.result.setdefault("ECUC-FOREIGN-REFERENCE-DEF", []).append(
            _find_text(c_ref, "SHORT-NAME"))
        _State.foreign_ref_type[_find_text(c_ref, "SHORT-NAME")] = \
            _find_text(c_ref, "DESTINATION-TYPE")

    # 選択参照
    for c_ref in c_elem.findall("REFERENCES/ECUC-CHOICE-REFERENCE-DEF"):
        _State.result.setdefault("ECUC-CHOICE-REFERENCE-DEF", []).append(
            _find_text(c_ref, "SHORT-NAME"))

    # シンボル参照
    for c_ref in c_elem.findall(
            "REFERENCES/ECUC-SYMBOLIC-NAME-REFERENCE-DEF"):
        _State.result.setdefault(
            "ECUC-SYMBOLIC-NAME-REFERENCE-DEF", []).append(
            _find_text(c_ref, "SHORT-NAME"))

    # インスタンス参照
    for c_ref in c_elem.findall("REFERENCES/ECUC-INSTANCE-REFERENCE-DEF"):
        _State.result.setdefault("ECUC-INSTANCE-REFERENCE-DEF", []).append(
            _find_text(c_ref, "SHORT-NAME"))

    # サブコンテナ (再帰呼出し)
    for c_sub in c_elem.findall("SUB-CONTAINERS"):
        _make_param_info_parse_sub_container(c_sub)


######################################################################
# ジェネレータ用 csv ファイルの生成
######################################################################
_DATA_TYPE_TABLE = {
    "ECUC-REFERENCE-DEF":               "REF",
    "ECUC-FOREIGN-REFERENCE-DEF":       "REF",
    "ECUC-CHOICE-REFERENCE-DEF":        "REF",
    "ECUC-SYMBOLIC-NAME-REFERENCE-DEF": "REF",
    "ECUC-INSTANCE-REFERENCE-DEF":      "REF",
    "ECUC-BOOLEAN-PARAM-DEF":           "BOOLEAN",
    "ECUC-INTEGER-PARAM-DEF":           "INT",
    "ECUC-FUNCTION-NAME-DEF":           "FUNCTION",
    "ECUC-ENUMERATION-PARAM-DEF":       "ENUM",
    "ECUC-STRING-PARAM-DEF":            "STRING",
    "ECUC-FLOAT-PARAM-DEF":             "FLOAT",
    "ECUC-LINKER-SYMBOL-DEF":           "STRING",
    None:                                "",
}


def make_csv(s_file_name, s_target_module):
    if not os.path.isfile(s_file_name):
        sys.exit("Argument error !! [{0}]".format(s_file_name))

    s_csv_file = os.path.join(
        os.path.dirname(s_file_name) or ".", s_target_module + ".csv")

    root = _parse_xml(s_file_name)

    _State.result = OrderedDict()
    _State.container_path = ""

    for c_mod in root.findall(
            "AR-PACKAGES/AR-PACKAGE/AR-PACKAGES/AR-PACKAGE/ELEMENTS/"
            "ECUC-MODULE-DEF"):
        if _find_text(c_mod, "SHORT-NAME") != s_target_module:
            continue
        for c_cont in c_mod.findall(
                "CONTAINERS/ECUC-PARAM-CONF-CONTAINER-DEF"):
            _State.container_path = _find_text(c_cont, "SHORT-NAME")
            _State.result[_State.container_path] = \
                _make_csv_add_parameter_info(c_cont, None)
            _make_csv_parse_parameter(c_cont)

    s_module_path = "/AUTOSAR/EcucDefs/{0}".format(s_target_module)
    s_csv_data = "{0},,,1\n".format(s_module_path)

    for s_param, a_info in _State.result.items():
        if a_info[0] not in _DATA_TYPE_TABLE:
            sys.exit("[{0}] {1}: {2}".format(__file__, "?", a_info[0]))
        if a_info[1] == "1" and a_info[2] == "1":
            s_csv_data += "{0}/{1},{2},{3},1\n".format(
                s_module_path, s_param, s_param.split("/")[-1],
                _DATA_TYPE_TABLE[a_info[0]])
        else:
            s_csv_data += "{0}/{1},{2},{3},{4},{5}\n".format(
                s_module_path, s_param, s_param.split("/")[-1],
                _DATA_TYPE_TABLE[a_info[0]], a_info[1], a_info[2])

    with open(s_csv_file, "w", encoding="utf-8", newline="\n") as fp:
        fp.write(s_csv_data)

    print("Generated {0}".format(s_csv_file))


def _make_csv_add_parameter_info(c_elem, s_name):
    if s_name is None:
        s_name = c_elem.tag

    s_lower = _find_text(c_elem, "LOWER-MULTIPLICITY")
    if s_lower is None:
        sys.exit("[{0}] LOWER-MULTIPLICITY missing".format(__file__))

    s_upper = None
    upper_text = _find_text(c_elem, "UPPER-MULTIPLICITY")
    if upper_text is not None:
        s_upper = upper_text
    else:
        upper_inf = _find_text(c_elem, "UPPER-MULTIPLICITY-INFINITE")
        if upper_inf == "true":
            s_upper = "*"
        else:
            sys.exit("[{0}] UPPER-MULTIPLICITY missing".format(__file__))

    return [s_name, s_lower, s_upper]


def _make_csv_parse_sub_container(c_elem):
    for c in list(c_elem):
        if c.tag == "ECUC-CHOICE-CONTAINER-DEF":
            _State.container_path = "{0}/{1}".format(
                _State.container_path, _find_text(c, "SHORT-NAME"))
            _State.result[_State.container_path] = \
                _make_csv_add_parameter_info(c, None)
            _make_csv_parse_sub_container(c)
            parts = _State.container_path.split("/")
            parts.pop()
            _State.container_path = "/".join(parts)
        elif c.tag == "ECUC-PARAM-CONF-CONTAINER-DEF":
            _State.container_path = "{0}/{1}".format(
                _State.container_path, _find_text(c, "SHORT-NAME"))
            _State.result[_State.container_path] = \
                _make_csv_add_parameter_info(c, None)
            _make_csv_parse_parameter(c)
            parts = _State.container_path.split("/")
            parts.pop()
            _State.container_path = "/".join(parts)
        else:
            _make_csv_parse_sub_container(c)


def _make_csv_parse_parameter(c_elem):
    for c_p in c_elem.findall("PARAMETERS"):
        for c_g in list(c_p):
            s_param = "{0}/{1}".format(
                _State.container_path, _find_text(c_g, "SHORT-NAME"))
            _State.result[s_param] = _make_csv_add_parameter_info(c_g, c_g.tag)

    for tag in ("ECUC-REFERENCE-DEF", "ECUC-FOREIGN-REFERENCE-DEF",
                "ECUC-CHOICE-REFERENCE-DEF",
                "ECUC-SYMBOLIC-NAME-REFERENCE-DEF",
                "ECUC-INSTANCE-REFERENCE-DEF"):
        for c_ref in c_elem.findall("REFERENCES/{0}".format(tag)):
            s_param = "{0}/{1}".format(
                _State.container_path, _find_text(c_ref, "SHORT-NAME"))
            _State.result[s_param] = _make_csv_add_parameter_info(
                c_ref, c_ref.tag)

    for c_sub in c_elem.findall("SUB-CONTAINERS"):
        _make_csv_parse_sub_container(c_sub)


######################################################################
# オプション処理
######################################################################
def _build_argparser():
    parser = argparse.ArgumentParser(
        prog="abrex.py",
        usage="abrex.py [options]... [yaml|xml files]...",
        description="ABREX: AUTOSAR BSW and RTE XML Generator",
    )
    parser.add_argument("-i", dest="xml_to_yaml", metavar="XML_FILE",
                        help="ARXML to YAML conversion")
    parser.add_argument("-p", dest="param_info", metavar="XML_FILE",
                        help="Generate 'param_info.yaml' from "
                             "AUTOSAR Ecu Configuration Parameters file")
    parser.add_argument("-c", dest="make_csv", metavar="XML_FILE",
                        help="Generate '{BSW_NAME}.csv' from AUTOSAR "
                             "Ecu Configuration Parameters file")
    parser.add_argument("-b", dest="bsw_name", metavar="BSW_NAME",
                        help="set a BSW Module Name "
                             "(for '-c' additional option)")
    parser.add_argument("-e", dest="ecu_extract_ref",
                        metavar="ECU-EXTRACT-REF",
                        help="set a ECU-EXTRACT-REF path if "
                             "<ECUC-VALUE-COLLECTION> is needed")
    parser.add_argument("-v", "--version", action="version",
                        version=VERSION)
    parser.add_argument("-V", "--verbose", action="store_true",
                        help="Show the warning on as conversion is running.")
    parser.add_argument("files", nargs="*",
                        help="YAML or XML files (used for default "
                             "YAML-to-XML conversion)")
    return parser


def main():
    parser = _build_argparser()
    args = parser.parse_args()

    # モード判定 (Ruby 版の挙動に合わせる)
    if args.xml_to_yaml is not None:
        xml_to_yaml(args.xml_to_yaml, args.files)
    elif args.param_info is not None:
        make_param_info(args.param_info)
    elif args.make_csv is not None:
        if args.bsw_name is None:
            parser.print_help()
            sys.exit(1)
        make_csv(args.make_csv, args.bsw_name)
    else:
        if not args.files:
            parser.print_help()
            sys.exit(1)
        yaml_to_xml(args.files, args.ecu_extract_ref, args.verbose)


if __name__ == "__main__":
    main()
